export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";

export const FETCH_ARTICLE = "FETCH_ARTICLE";
export const FETCH_ARTICLE_SUCCESS = "FETCH_ARTICLE_SUCCESS";

export const FETCH_WORD = "FETCH_WORD";
export const FETCH_WORD_SUCCESS = "FETCH_WORD_SUCCESS";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
