export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
